# Generated by Django 2.2.2 on 2019-11-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0004_auto_20191115_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='projects',
        ),
        migrations.AddField(
            model_name='article',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fellows.Profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fellows.WorkExperience'),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, to='fellows.Author'),
        ),
    ]
