# Generated by Django 2.2.2 on 2019-11-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0005_auto_20191115_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fellows.Profile'),
        ),
    ]
