# Generated by Django 2.2.2 on 2019-11-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0006_workexperience_work_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='work_experience',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='article',
            name='dziedzina',
        ),
        migrations.AddField(
            model_name='article',
            name='field',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='adress',
            name='apartment',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='adress',
            name='house_nummer',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, default=None, to='fellows.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('city', models.CharField(max_length=25)),
                ('degree_cours', models.CharField(max_length=25)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('students_group', models.CharField(blank=True, default='', max_length=125)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fellows.Profile')),
            ],
        ),
    ]
